openapi: 3.0.1
info:
  title: NicImages
  version: 0.1.0
servers:
  - url: "{server}:{port}/nic"
    variables:
      server:
        default: http://localhost
      port:
        default: "9090"
paths:
  /upload:
    post:
      operationId: uploadNIC
      summary: A resource for handling upload of nic files
      parameters:
        - name: requestID
          in: query
          required: true
          schema:
            type: string
      requestBody:
        content:
          image/*:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
          '200':
            description: Ok
            content:
              application/json:
                schema:
                  type: string
                  format: binary
          "500":
            description: Internal server error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ErrorPayload"
  /download:
    get:
      operationId: downloadNIC
      summary: A resource for handling download of nic files
      parameters:
        - name: requestID
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Ok
          content:
            image/*:
              schema:
                type: object
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorPayload"
  /liveness:
    get:
      operationId: getLiveness
      responses:
        "200":
          description: Ok

components:
  schemas:
    ErrorPayload:
      type: object
      properties:
        reason:
          type: string
          description: Reason phrase
        path:
          type: string
          description: Request path
        method:
          type: string
          description: Method type of the request
        message:
          type: string
          description: Error message
        timestamp:
          type: string
          description: Timestamp of the error
        status:
          type: integer
          description: Relevant HTTP status code
          format: int32